"""Single configuration catalog used by browser previews and ASS rendering."""

from typing import Any

from clipforge_api.clip_schemas import CaptionConfig

DESIGNS: list[tuple[str, str, str, dict[str, Any]]] = [
    (
        "creator-impact",
        "Creator Impact",
        "Creator",
        dict(
            size=76,
            max_words=3,
            lines=1,
            uppercase=True,
            outline=5,
            highlight=True,
            animation="word-pop",
            y=0.66,
        ),
    ),
    (
        "viral-yellow",
        "Viral Yellow",
        "Viral",
        dict(
            size=80,
            primary_color="#FFE600",
            max_words=3,
            outline=5,
            uppercase=True,
            animation="pop",
            y=0.68,
        ),
    ),
    (
        "creator-white",
        "Creator White",
        "Creator",
        dict(size=68, max_words=4, lines=1, outline=4, shadow=3, y=0.70),
    ),
    (
        "bold-impact",
        "Bold Impact",
        "Creator",
        dict(
            size=88,
            max_words=2,
            lines=1,
            highlight=True,
            highlight_color="#00EAFF",
            outline=6,
            animation="pop",
            uppercase=True,
            y=0.65,
        ),
    ),
    (
        "study-clean",
        "Study Clean",
        "Educational",
        dict(
            size=48,
            font="Noto Sans",
            weight=400,
            outline=1,
            shadow=0,
            highlight=True,
            highlight_color="#FBCB76",
            animation="fade",
        ),
    ),
    (
        "minimal-white",
        "Minimal White",
        "Clean",
        dict(size=44, weight=400, outline=1, shadow=0, spacing=1.5, max_words=7, animation="fade"),
    ),
    (
        "minimal-dark",
        "Minimal Dark",
        "Clean",
        dict(
            size=46,
            primary_color="#181D24",
            background=True,
            background_color="#FFFFFF",
            background_opacity=0.94,
            outline=0,
            shadow=0,
            max_words=6,
        ),
    ),
    (
        "podcast-bold",
        "Podcast Bold",
        "Podcast",
        dict(
            size=62,
            max_words=4,
            outline=3,
            background=True,
            background_opacity=0.75,
            highlight=True,
            y=0.72,
        ),
    ),
    (
        "podcast-clean",
        "Podcast Clean",
        "Podcast",
        dict(size=48, max_words=6, weight=400, background=True, outline=0, shadow=0, y=0.76),
    ),
    (
        "yellow-focus",
        "Yellow Focus",
        "Viral",
        dict(
            size=64,
            max_words=3,
            lines=1,
            highlight=True,
            highlight_color="#FFDA00",
            animation="karaoke",
            y=0.69,
        ),
    ),
    (
        "green-focus",
        "Green Focus",
        "Gaming",
        dict(
            size=70,
            max_words=3,
            primary_color="#DDFFEA",
            highlight=True,
            highlight_color="#41FF73",
            stroke_color="#082C18",
            outline=5,
            animation="word-pop",
        ),
    ),
    (
        "blue-focus",
        "Blue Focus",
        "Business",
        dict(
            size=52,
            font="Noto Sans",
            primary_color="#E9F2FF",
            highlight_color="#48ADFF",
            highlight=True,
            background=True,
            background_color="#10243D",
            animation="karaoke",
        ),
    ),
    (
        "word-pop",
        "Word Pop",
        "Viral",
        dict(
            size=82, max_words=1, lines=1, uppercase=True, animation="word-pop", outline=4, y=0.64
        ),
    ),
    (
        "karaoke",
        "Karaoke",
        "Creator",
        dict(
            size=60,
            max_words=5,
            animation="karaoke",
            highlight=True,
            highlight_color="#FFB800",
            y=0.72,
        ),
    ),
    (
        "clean-karaoke",
        "Clean Karaoke",
        "Clean",
        dict(
            size=46,
            weight=400,
            outline=1,
            animation="karaoke",
            highlight=True,
            highlight_color="#6CE4DA",
            max_words=7,
        ),
    ),
    (
        "cinematic",
        "Cinematic",
        "Cinematic",
        dict(
            size=42,
            spacing=3,
            weight=400,
            max_words=8,
            outline=1,
            shadow=0,
            primary_color="#F1E8D9",
            animation="fade",
            y=0.80,
        ),
    ),
    (
        "documentary",
        "Documentary",
        "Cinematic",
        dict(
            size=46,
            font="Noto Sans",
            weight=400,
            max_words=8,
            background=True,
            background_opacity=0.5,
            outline=0,
            shadow=0,
            alignment="left",
            x=0.10,
            width=0.8,
        ),
    ),
    (
        "business-pro",
        "Business Pro",
        "Business",
        dict(
            size=50,
            max_words=6,
            font="Noto Sans",
            background=True,
            background_color="#18324C",
            outline=0,
            shadow=0,
            animation="slide",
            alignment="left",
            x=0.10,
        ),
    ),
    (
        "educational",
        "Educational",
        "Educational",
        dict(
            size=52,
            max_words=5,
            highlight=True,
            primary_color="#F9FAFC",
            highlight_color="#FFD084",
            background=True,
            background_color="#253449",
            outline=1,
        ),
    ),
    (
        "storytelling",
        "Storytelling",
        "Cinematic",
        dict(
            size=56,
            max_words=4,
            weight=400,
            primary_color="#FFEAD2",
            outline=2,
            animation="fade",
            y=0.70,
        ),
    ),
    (
        "gaming",
        "Gaming Pulse",
        "Gaming",
        dict(
            size=72,
            max_words=3,
            uppercase=True,
            primary_color="#65FFF3",
            stroke_color="#28104E",
            outline=6,
            shadow=4,
            animation="bounce",
            y=0.65,
        ),
    ),
    (
        "news",
        "News Desk",
        "Business",
        dict(
            size=46,
            max_words=8,
            background=True,
            background_color="#9D2032",
            background_opacity=0.98,
            outline=0,
            shadow=0,
            alignment="left",
            x=0.08,
            y=0.78,
        ),
    ),
    (
        "reels-modern",
        "Reels Modern",
        "Creator",
        dict(
            size=64,
            max_words=4,
            highlight=True,
            highlight_color="#FFA0C9",
            spacing=1,
            outline=3,
            animation="scale",
            y=0.68,
        ),
    ),
    (
        "social-bold",
        "Social Bold",
        "Viral",
        dict(
            size=84,
            max_words=2,
            lines=1,
            primary_color="#FFFFFF",
            highlight_color="#FF406C",
            highlight=True,
            uppercase=True,
            outline=5,
            animation="word-pop",
            y=0.65,
        ),
    ),
    (
        "high-contrast",
        "High Contrast",
        "Clean",
        dict(
            size=64,
            max_words=4,
            background=True,
            background_opacity=1,
            primary_color="#FFFF00",
            outline=0,
            shadow=0,
            y=0.73,
        ),
    ),
]

TEMPLATES = [
    {
        "id": key,
        "name": name,
        "category": category,
        "config": CaptionConfig(template_id=key, **values).model_dump(mode="json"),
    }
    for key, name, category, values in DESIGNS
]
