"""job_heartbeat_recovery"""

import sqlalchemy as sa
from alembic import op

revision = "68fe9c8a63bf"
down_revision = "cd1c17ebf520"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_jobs", "heartbeat_at")
    # ### end Alembic commands ###
