"""multipart upload sessions"""

import sqlalchemy as sa
from alembic import op

revision = "ecdf4f80a0c1"
down_revision = "32ec7031bf16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_sessions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("upload_id", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("part_size", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["media_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_sessions_project_id"), "upload_sessions", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_upload_sessions_project_id"), table_name="upload_sessions")
    op.drop_table("upload_sessions")
    # ### end Alembic commands ###
