import type { CaptionStyle } from "./editor-types";
import type { CaptionAnimation } from "./caption-effects";

export { CAPTION_FONTS } from "./caption-fonts";
export const DEFAULT_CAPTION: CaptionStyle = {
  enabled: true,
  style: "Clean",
  font: "DejaVu Sans",
  size: 54,
  weight: 700,
  font_width: 100,
  italic: false,
  max_words: 5,
  max_chars_per_line: 24,
  lines: 2,
  position: "bottom",
  uppercase: false,
  punctuation: true,
  remove_special_characters: false,
  outline: 3,
  stroke_color: "#141414",
  shadow: 1,
  shadow_color: "#000000",
  shadow_opacity: 0.6,
  background: false,
  background_color: "#000000",
  background_opacity: 0.65,
  highlight: false,
  primary_color: "#FFFFFF",
  highlight_color: "#FFD700",
  spacing: 0,
  animation: "word-pop",
  animation_duration: 0.4,
  effect_color: "#0054FF",
  word_display: "full",
  active_scale: 1.06,
  inactive_opacity: 1,
  x: 0.5,
  y: 0.78,
  width: 0.84,
  alignment: "center",
  safe_bottom: 0.17,
};
export type CaptionTemplate = {
  id: string;
  name: string;
  category: string;
  description: string;
  accent: string;
  sample: string;
  config: CaptionStyle;
};
function preset(
  id: string,
  name: string,
  category: string,
  description: string,
  accent: string,
  sample: string,
  animation: CaptionAnimation,
  config: CaptionStyle,
): CaptionTemplate {
  return {
    id,
    name,
    category,
    description,
    accent,
    sample,
    config: {
      ...DEFAULT_CAPTION,
      font: "Urbanist",
      size: 72,
      outline: 3,
      lines: 1,
      max_words: 3,
      max_chars_per_line: 20,
      highlight: true,
      animation_duration: 0.24,
      animation,
      ...config,
      style: name,
    },
  };
}
export const CAPTION_TEMPLATES: CaptionTemplate[] = [
  preset(
    "studio-rise",
    "Studio Rise",
    "Clean",
    "Each spoken word rises into the sentence.",
    "#BBE9D4",
    "Make every moment count",
    "word-rise",
    {
      size: 72,
      outline: 2,
      shadow: 2,
      word_display: "build",
      highlight_color: "#BBE9D4",
    },
  ),
  preset(
    "creator-pop",
    "Creator Pop",
    "Creator",
    "Bold type. A spring on every spoken word.",
    "#FFE36E",
    "This is your moment",
    "word-spring",
    {
      font: "Montserrat",
      size: 82,
      outline: 5,
      uppercase: true,
      active_scale: 1.12,
      highlight: true,
      highlight_color: "#FFE36E",
      max_words: 3,
    },
  ),
  preset(
    "neon-focus",
    "Neon Focus",
    "Expressive",
    "One electric word. Full attention.",
    "#73FFB8",
    "Ideas worth sharing",
    "word-focus",
    {
      primary_color: "#73FFB8",
      stroke_color: "#154B3C",
      highlight_color: "#73FFB8",
      word_display: "single",
      size: 108,
      outline: 4,
      uppercase: true,
    },
  ),
  preset(
    "editorial",
    "Editorial",
    "Clean",
    "A fine underline tracks the speaker.",
    "#D5D0C7",
    "A different perspective",
    "word-underline",
    {
      font: "Lato",
      weight: 400,
      size: 64,
      highlight_color: "#F2EDE4",
      effect_color: "#D5D0C7",
      active_scale: 1,
      outline: 0,
      spacing: 1.5,
      primary_color: "#F2EDE4",
    },
  ),
  preset(
    "kinetic-bold",
    "Kinetic Bold",
    "Creator",
    "Oversized single-word impact, on the beat.",
    "#FF9E7A",
    "MAKE YOUR MOVE",
    "word-punch",
    {
      font: "Bebas Neue",
      weight: 400,
      size: 96,
      word_display: "single",
      highlight_color: "#FF9E7A",
      uppercase: true,
      max_words: 3,
      primary_color: "#FF9E7A",
      outline: 4,
    },
  ),
  preset(
    "lavender-lift",
    "Lavender Lift",
    "Expressive",
    "Soft lilac words build a thought in rhythm.",
    "#D5BAFF",
    "Create your own rhythm",
    "word-rise",
    {
      primary_color: "#FFFFFF",
      highlight_color: "#D5BAFF",
      font: "Montserrat",
      size: 72,
      outline: 2,
      word_display: "build",
      lines: 2,
      max_words: 2,
      inactive_opacity: 0.7,
    },
  ),
  preset(
    "karaoke-gold",
    "Karaoke Gold",
    "Karaoke",
    "A golden pill follows the conversation.",
    "#FFD76C",
    "Every word tells a story",
    "word-pill",
    {
      font: "Montserrat",
      highlight: true,
      highlight_color: "#171A13",
      effect_color: "#FFD76C",
      size: 72,
      outline: 0,
      shadow: 0,
      active_scale: 1.04,
    },
  ),
  preset(
    "podcast-card",
    "Podcast Card",
    "Clean",
    "Crisp white words with a cobalt tracking block.",
    "#AFCBEB",
    "Let's talk about it",
    "word-box",
    {
      font: "Open Sans",
      size: 64,
      effect_color: "#275CF5",
      highlight_color: "#FFFFFF",
      inactive_opacity: 0.6,
      active_scale: 1,
      background_color: "#14212E",
      background_opacity: 0.94,
      outline: 0,
    },
  ),
  preset(
    "type-notes",
    "Type Notes",
    "Editorial",
    "An intimate word-by-word reading rhythm.",
    "#E3DCBE",
    "A small thought. A big idea.",
    "word-focus",
    {
      font: "Lato",
      weight: 400,
      size: 68,
      word_display: "build",
      highlight_color: "#F4EACD",
      primary_color: "#F4EACD",
      outline: 0,
      animation_duration: 0.22,
    },
  ),
  preset(
    "cobalt-ink",
    "Cobalt Ink",
    "Expressive",
    "White-on-cobalt blocks accent each word.",
    "#719DFF",
    "Something extraordinary",
    "word-box",
    {
      font: "Urbanist",
      effect_color: "#2455EE",
      highlight_color: "#FFFFFF",
      size: 90,
      word_display: "single",
      uppercase: true,
      outline: 0,
      animation_duration: 0.2,
    },
  ),
  preset(
    "word-cascade",
    "Word Cascade",
    "Creator",
    "Words slide into a two-line, speech-timed stack.",
    "#A6E8FF",
    "Start before you feel ready",
    "word-slide",
    {
      font: "Roboto",
      highlight: false,
      size: 76,
      word_display: "build",
      lines: 2,
      primary_color: "#D9F6FF",
      max_words: 2,
    },
  ),
  preset(
    "spotlight",
    "Spotlight",
    "Karaoke",
    "The spoken word takes center stage.",
    "#FFB9E8",
    "Your voice matters",
    "word-spring",
    {
      font: "Montserrat",
      size: 80,
      inactive_opacity: 0.3,
      active_scale: 1.15,
      highlight_color: "#FFB9E8",
      max_words: 3,
      outline: 1,
    },
  ),
  preset(
    "cinema-soft",
    "Cinema Soft",
    "Editorial",
    "Warm, restrained words with a soft focus pull.",
    "#E9C5A4",
    "Some moments stay with us",
    "word-focus",
    {
      font: "Lato",
      weight: 400,
      size: 60,
      word_display: "build",
      highlight: false,
      spacing: 3,
      outline: 1,
      animation_duration: 0.3,
      primary_color: "#FFF1DD",
    },
  ),
  preset(
    "social-bounce",
    "Social Bounce",
    "Creator",
    "Big lime energy. One bouncing word at a time.",
    "#D6FF70",
    "Go make it happen",
    "word-spring",
    {
      font: "Montserrat",
      size: 100,
      word_display: "single",
      highlight_color: "#D6FF70",
      active_scale: 1.12,
      outline: 5,
      primary_color: "#D6FF70",
      uppercase: true,
      max_words: 3,
    },
  ),
  preset(
    "coral-slide",
    "Coral Slide",
    "Expressive",
    "Coral words slide in as the sentence builds.",
    "#FFAD9F",
    "Find a new direction",
    "word-slide",
    {
      font: "Urbanist",
      size: 74,
      primary_color: "#FFFFFF",
      highlight_color: "#FFAD9F",
      outline: 2,
      word_display: "build",
    },
  ),
  preset(
    "arctic-slide",
    "Arctic Slide",
    "Clean",
    "An icy glow moves from word to word.",
    "#B8E8F0",
    "Clarity changes everything",
    "word-glow",
    {
      font: "Roboto",
      size: 72,
      highlight_color: "#E1FAFF",
      effect_color: "#55D9FF",
      inactive_opacity: 0.45,
      primary_color: "#E1FAFF",
      outline: 0,
      spacing: 1,
    },
  ),
  preset(
    "headline-drop",
    "Headline Drop",
    "Editorial",
    "Condensed headlines flip open, word by word.",
    "#FFFFFF",
    "THE NEXT CHAPTER",
    "word-flip",
    {
      font: "Bebas Neue",
      weight: 400,
      uppercase: true,
      size: 90,
      word_display: "build",
      highlight_color: "#FFFFFF",
      max_words: 4,
      outline: 3,
      spacing: 2,
    },
  ),
  preset(
    "paper-cut",
    "Paper Cut",
    "Editorial",
    "Warm paper blocks jump to the spoken word.",
    "#F5DFB4",
    "Good things take time",
    "word-box",
    {
      font: "Lato",
      primary_color: "#F5DFB4",
      highlight_color: "#252321",
      effect_color: "#F5DFB4",
      background_color: "#F5DFB4",
      background_opacity: 1,
      outline: 0,
      shadow: 0,
      size: 74,
      active_scale: 1,
    },
  ),
  preset(
    "tilt-talk",
    "Tilt Talk",
    "Creator",
    "A playful tilt on every word, with orange punch.",
    "#FFB65C",
    "Here's the interesting part",
    "word-tilt",
    {
      font: "Montserrat",
      size: 80,
      word_display: "build",
      highlight_color: "#FFB65C",
      primary_color: "#FFFFFF",
      max_words: 4,
      outline: 3,
    },
  ),
  preset(
    "unfold",
    "Unfold",
    "Expressive",
    "Each spoken word unfolds into a lilac stack.",
    "#B6A6FF",
    "More than meets the eye",
    "word-flip",
    {
      font: "Urbanist",
      size: 80,
      word_display: "build",
      highlight_color: "#B6A6FF",
      lines: 2,
      max_words: 2,
      primary_color: "#DDD4FF",
      outline: 1,
      spacing: 1,
    },
  ),
  preset(
    "elastic-type",
    "Elastic Type",
    "Expressive",
    "Single-word elastic type with a mint finish.",
    "#94F2D2",
    "Built to stand out",
    "word-stretch",
    {
      font: "Bebas Neue",
      weight: 400,
      size: 112,
      word_display: "single",
      highlight_color: "#94F2D2",
      uppercase: true,
      primary_color: "#94F2D2",
      outline: 0,
      max_words: 4,
    },
  ),
  preset(
    "rose-karaoke",
    "Rose Karaoke",
    "Karaoke",
    "Rose-pink pills carry the spoken word.",
    "#FCABCA",
    "Follow the feeling",
    "word-pill",
    {
      font: "Noto Sans",
      size: 72,
      highlight: true,
      highlight_color: "#311C35",
      effect_color: "#FCABCA",
      inactive_opacity: 0.55,
      shadow: 0,
      background_color: "#311C35",
      background_opacity: 0.9,
      outline: 0,
    },
  ),
  preset(
    "documentary",
    "Documentary",
    "Editorial",
    "Natural speech with a precise green underline.",
    "#CED9E0",
    "There's always more to the story",
    "word-underline",
    {
      font: "Open Sans",
      weight: 400,
      size: 62,
      highlight_color: "#FFFFFF",
      effect_color: "#80D6B6",
      active_scale: 1,
      max_words: 7,
      max_chars_per_line: 36,
      outline: 2,
      animation_duration: 0.3,
    },
  ),
  preset(
    "after-hours",
    "After Hours",
    "Clean",
    "Ivory italics arrive one word at a time.",
    "#EFE2C4",
    "Stay a little longer",
    "word-rise",
    {
      font: "Lato",
      italic: true,
      weight: 400,
      size: 78,
      word_display: "single",
      highlight_color: "#EFE2C4",
      primary_color: "#EFE2C4",
      spacing: 1,
      outline: 0,
      animation_duration: 0.3,
    },
  ),
];

/** Apply appearance without changing an existing clip's transcript. */
export function applyCaptionTemplate(
  current: CaptionStyle,
  config: CaptionStyle,
): CaptionStyle {
  return { ...config, enabled: current.enabled ?? true, cues: current.cues };
}
